release: python backend/manage.py collectstatic --noinput && python backend/manage.py migrate
web: gunicorn project_config.wsgi --log-file - --pythonpath backend
worker: python backend/manage.py start_websocket