# Generated by Django 5.2.6 on 2025-10-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_return_pct_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cryptodata',
            name='core_crypto_symbol_idx',
        ),
        migrations.RemoveIndex(
            model_name='cryptodata',
            name='core_crypto_symbol_vol_idx',
        ),
        migrations.RemoveIndex(
            model_name='cryptodata',
            name='core_crypto_volume_idx',
        ),
        migrations.RemoveIndex(
            model_name='cryptodata',
            name='core_crypto_price_idx',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m10_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m15_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m1_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m2_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m3_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m5_r_pct',
        ),
        migrations.RemoveField(
            model_name='cryptodata',
            name='m60_r_pct',
        ),
    ]
