# Generated by Django 5.2.6 on 2025-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cryptodata_core_crypto_symbol_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodata',
            name='m10_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='10 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m15_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='15 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m1_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='1 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m2_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='2 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m3_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='3 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m5_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='5 minute return percentage', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='m60_r_pct',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='60 minute return percentage', max_digits=20, null=True),
        ),
    ]
