# Generated by Django 4.2 on 2025-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cryptodata_m10_r_pct_cryptodata_m15_r_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='User Telegram Chat ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for notifications', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_connected',
            field=models.BooleanField(default=False, help_text='Is Telegram connected for alerts'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_setup_token',
            field=models.CharField(blank=True, help_text='Token for Telegram setup verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram Username (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price_movement', 'Price Movement'), ('volume_change', 'Volume Change'), ('new_coin_listing', 'New Coin Listing'), ('rsi_overbought', 'RSI Overbought (>70)'), ('rsi_oversold', 'RSI Oversold (<30)'), ('pump_alert', 'Pump Alert (>5% in 1m)'), ('dump_alert', 'Dump Alert (<-5% in 1m)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='notification_channels',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('both', 'Email + Telegram')], default='email', max_length=50),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_active'], name='core_alert_alert_t_b49238_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['coin_symbol', 'is_active'], name='core_alert_coin_sy_d50392_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_active'], name='core_alert_user_id_5100c2_idx'),
        ),
    ]
